project:
  title: "Procrastination and Dementia"
  type: website
  output-dir: "docs"
  pre-render:
    - "quarto render manuscript" # Will render manuscript to docs/manuscript

  render:
    - "**/*.qmd"
    - "!manuscript"

  resources:
   # We need to include the libs folder so that the html file renders correctly
    - "manuscript/output/manuscript_files"
    - "manuscript/output/"

  preview:
    port: 44
    browser: true
    watch-inputs: false
    navigate: true

execute:
  freeze: auto  # Re-render only when source changes

website:
  repo-url: "https://github.com/C-Monaghan/crisp-clam"
  repo-actions: [edit, issue]

  page-navigation: true
  bread-crumbs: false

  navbar:
    pinned: true
    background: "#1D6996"
    search: true

    left:
      - text: "Data"
        file: "analysis/data-final.qmd"
      - text: "Hypotheses"
        file: "analysis/hypothesis.qmd"
      - text: "Analysis"
        file: "analysis/data-analysis.qmd"
      - text: "Manuscript"
        file: "analysis/manuscript.qmd"

    right:
      - icon: github
        aria-label: github
        href: https://github.com/C-Monaghan/crisp-clam

  sidebar:
    - title: "Analysis"
      style: docked
      background: dark
      contents:
        - section: "Analysis plan"
          contents:
            - analysis/data-analysis.qmd

        - section: "Statistical models"
          contents:
            - analysis/kruskal-wallis.qmd
            - analysis/discrete-markov.qmd

    - title: "Empty space"

  page-footer:
    left:  |
      Content {{< fa brands creative-commons >}} 2024â€“2025 by Cormac Monaghan, Rafael de Andrade Moral, Michelle Kelly, and Joanna McHugh Power<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}}
      [Creative Commons Attribution 4.0 International license (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/C-Monaghan/crisp-clam)

format:
  html:
    theme:
      - zephyr
      - html/theme.scss
    toc: true
    toc-title: On this page
    toc-location: right
    code-tools: true
    code-copy: true
    highlight-style: monokai
